[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "site/_data"

[[redirects]]
  from = "/rss-feeds.json"
  to = "/feeds.json"
  status = 200  