[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "site/_data"

    # All the feeds we wish to gather for use in the build

    [[plugins.inputs.feeds]]
      name = "rebelnews"
      url = "https://www.rebelnews.com/news.rss"
      ttl = 3600
    [[plugins.inputs.feeds]]
      name = "thegatewaypundit"
      url = "https://www.thegatewaypundit.com/feed/"
      ttl = 86400
      [[plugins.inputs.feeds]]
      name = "thepostmillennial"
      url = "https://thepostmillennial.com/index.rss"
      ttl = 86400
