[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "site/_data"
    # URLs of RSS feeds to fetch
    feeds = [
      "https://jade-tartufo-c04725.netlify.app/rss-feeds.toml"
    ]

[[redirects]]
  from = "/rss-feeds.json"
  to = "/feeds.json"
  status = 200  