[feeds.feed1]
url = "https://www.rebelnews.com/news.rss"

[feeds.feed2]
url = "https://www.rebelnews.com/news.rss"

[feeds.feed3]
url = "https://thepostmillennial.com/index.rss"

# Add more feeds here

limit = 10
sortBy = "pubDate"
sortOrder = "desc"
